#!/usr/bin/perl -w

# Copyright information contained at the end of the file

# Import Module
use Getopt::Long;
use Pod::Usage;
use IO::Socket;
use strict;

# Set global variables for 'use strict'

use vars qw ($Debug $socketDir $socketFile $socket $requestType $currentFile $recData
             $searchString $sentData $refreshServer $killServer);

# Set global variables
$Debug = 0;
$socketDir = $ENV{'VERPARSE_SOCKET'};
    # See if the $sockedDir environment variable has been set, if not, exit
    die "The VERPARSE_SOCKET environment variable isn't set! Exitting..." unless $socketDir;

$socketFile = "$socketDir/socket";

# Get command line options
if (! GetOptions (
          "help"     => \&usage,
          "debug"    => \&debug,
          "t=s"      => \$requestType,
          "f=s"      => \$currentFile,
          "s=s"      => \$searchString,
          "kill!"    => \$killServer,
          "refresh!" => \$refreshServer
    )) {
    die "%Error: Bad usage, try 'vnetsearch --help'\n";
}

# Setup up communication port
createSocket();

# Send input data to the server
if ($killServer) {
    $sentData = "kill=1";
} elsif ($refreshServer) {
    $sentData = "refresh=1";
} elsif ($currentFile) {
    $sentData = "type=$requestType;search=$searchString;file=$currentFile";
} else {
    $sentData = "type=$requestType;search=$searchString";
}

print "Data sent to verparse_server: $sentData\n" if $Debug;
print $socket "$sentData\n";

# Receive data from the server
chomp ($recData = <$socket>);
print "Data received from server   : $recData\n" if $Debug;
print $recData, "\n";

######################################################################

# Display POD

sub usage {
    pod2usage(-verbose=>2, -exitval=> 2);
    exit (1);
}

######################################################################

# Enable debug output

sub debug {
    $Debug = 1;
}

######################################################################

# Setup UNIX domain socket

sub createSocket {
    
    # Check and see if the UNIX domain socket file exists, if not, exit client
    if (-S $socketFile) {
        $socket = IO::Socket::UNIX->new(Peer => $socketFile,
                                        Type => SOCK_STREAM
                                       ) or die ( "Can't connect to server: $!\n");
        
    } else {
        print "No verparse_server running...\n\nExitting...\n";
        exit (1);
    }
}

######################################################################
######################################################################
######################################################################

__END__

=pod

=head1 NAME

verparse - Sends parsing requests to the running verparse_server

=head1 SYNOPSIS

  verparse --help
  verparse --refresh
  verparse [--debug] -f file -t request_type -s search_string

=head1 DESCRIPTION

verparse sends search requests to a running verparse_server and
receives data regarding which verilog file and line number from the
search result.

=head1 DISTRIBUTION

Verilog-Perl is part of the L<http://www.veripool.org/> free Verilog EDA
software tool suite. The latest version is availabe from CPAN and from
L<http://www.veripool.org/verilog-perl>.

Copyright 2011 by Chuck McClish. This package is free software; you
can redistribute it and/or modify it under the terms of either the GNU
Lesser General Public License Version 3 or the Perl Artistic License Version 2.0.

=head1 AUTHOR

Chuck McClish <charles.mcclish@microchip.com>

=head1 SEE ALSO

L<Verilog-Perl>,
L<Verilog::Getopt>,
L<Verilog::Netlist>,
L<IO::Socket>

=cut
######################################################################
